### ISSUE TITLE
Offline Transaction

### ISSUE THREAD

**Issue by aghamir** [ParsiCoin/parsipay#1]
Hi,
I very interest in your new cryptocion. I have two question about your coin and wallet. First, can I do offline signing transaction with your parsipay wallet(I mean a mechanism likes electrum or MEW)? Second, what is the network below your ParsiCoin? Is it ethereum custom symbol?
Thanks, a lot.

**Comment by ParsiCoin** [comment]
No You can't do offline signing transaction with GUI Wallet, ParsiCoin Based on CryptoNote.
