### ISSUE TITLE
Parsipay : no choice to restore a wallet from seed at first run

### ISSUE THREAD

**Issue by citizenz7** [ParsiCoin/parsipay#6]
When opening Parsipay for the first time, you have to create a new wallet... and then you have choice to restore a wallet from seed.
You can not restore a wallet from seed directly.

**Comment by ParsiCoin** [comment]
You can Restore Your Wallet From Seeds, but you need to create a wallet file while you are restoring your wallet. you need to choose a path for wallet and you should also give your wallet file a name.

**Comment by ParsiCoin** [comment]
![parsipay](https://user-images.githubusercontent.com/36328859/48099371-97ef0180-e234-11e8-891e-e1f96804816d.png)

**Comment by citizenz7** [comment]
Ok, thanx !
